S2C_MSG_ID = {
	S2C_MSG_HEART = 1,	--心跳
	S2C_MSG_LOADING=3,
	S2C_MSG_PLAYER_LIST = 4, --获取玩家列表
	S2C_MSG_EMOJI =5, --表情协议,收到其他玩家的表情
	S2C_MSG_START = 7, --游戏开始
	S2C_MSG_OUT=8, --退出游戏
	S2C_MSG_GAME_WIN=9, --游戏胜利
	S2C_MSG_GAME_SIGN_ERROR=10, --鉴权失败 表示非法连接(我猜的)
	S2C_MSG_PLAYER_RELOGIN = 11, --断线重连
	S2C_MSG_GET_PLAYER_STARTCARD = 12,	--获取玩家开始的手牌
	S2C_MSG_PLAYER_POKER_OPERA = 13, --手牌操作
	S2C_MSG_CLICK_CARD=14, --其他玩家点击牌
	S2C_MSG_REFRESH_POKER = 15, --更新玩家手牌
	S2C_MSG_AICHOOSE_CARD = 16,  --AI抽牌
	S2C_MSG_GAME_LOSE = 17, --断线通知,通知有其他客户端断线,然后将其转为AI
	S2C_MSG_GAEM_CARD_TOON=18,	--同步牌动画
	S2C_MSG_GAEM_NEXT_ROUND=19,	--玩家开始新回合
	S2C_MSG_GAEM_WASH_POKER=20,	--洗牌
	S2C_MSG_GAEM_PLAYER_OVER=21, --玩家胜利
}


CLIENT_2_SERVER={
	HEARTBEAT=1000,
	LOADING=1001,
	QUIT=1002, --退出游戏
	EMOJI=1003,	--发送表情
	GAME_START=1004,	--游戏开始
	GAME_CHOOSE_POKER=1005,		--抽牌协议
	GAME_CLICK_POKER=1006,	--同步点击牌事件
	GAEM_CARD_TOON=1007, --同步牌动画
	GAEM_WASH_POKER=1008,
}


GAME_STATE={
	START=1,
	WAITING=2,
	SHUFFLE=3,
	SHUFFLE_COMPLETED=4,
	CHOOSE_CARD=5, --选牌阶段
	DRAW_CARD=6,	--抽牌
	DRAW_CARD_COMPLETED=7,
	PLAY_CARD=8,	--出牌
	PLAY_CARD_COMPLETED=9,
	NEXT_PLAYER_START=10, --下一个玩家回合
	WIN=11,
	FAILED=12,	
	LOSE=13,	--玩家掉线
	RELOGIN=14, --断线重连
}	


